### ISSUE TITLE
Visualization problem

### ISSUE THREAD

**Issue by chuanbosi666** [cvlab-yonsei/DKD#1]
hello,I have a question.How do I visualize the trained log file?
Looking forward to your answer

**Comment by dh-baek** [comment]
To view .log files, you can simply open them with a text reader program such as Notepad, Sublime Text, or Visual Studio Code.

**Comment by dh-baek** [comment]
As far as I know, the visualization part of the configuration file (config_voc.json or config_ade.json) has not been changed. However, as I do not check it myself, I cannot give you an accurate answer.

That being said, to enable the visualization, you may need to replace the part that says "tensorboard" in the configuration file with true. This should allow the visualization to work properly.
